//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskClaim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskClaim()
        {
            this.TaskCheckpoint = new HashSet<TaskCheckpoint>();
            this.TaskClaim1 = new HashSet<TaskClaim>();
            this.TaskComment = new HashSet<TaskComment>();
            this.TaskFile = new HashSet<TaskFile>();
            this.TaskPlan = new HashSet<TaskPlan>();
            this.TaskAction = new HashSet<TaskAction>();
            this.TaskSpecification = new HashSet<TaskSpecification>();
        }
    
        public int TaskId { get; set; }
        public string Name { get; set; }
        public string Descr { get; set; }
        public Nullable<int> TaskCategoryId { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> DateStartPlan { get; set; }
        public Nullable<System.DateTime> DateEndPlan { get; set; }
        public Nullable<System.DateTime> DateStartFact { get; set; }
        public Nullable<System.DateTime> DateEndFact { get; set; }
        public string SpecialistSid { get; set; }
        public Nullable<int> TaskStateId { get; set; }
        public string ModifierSid { get; set; }
        public string CreatorSid { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<int> TaskImportantId { get; set; }
        public Nullable<int> TaskQuicklyId { get; set; }
        public int ProjectId { get; set; }
        public Nullable<int> ParentTaskId { get; set; }
        public Nullable<int> ParentTask_TaskId { get; set; }
        public int Rank { get; set; }
        public string RankChangerSid { get; set; }
        public Nullable<System.DateTime> RankChangeDate { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> QuantityTypeId { get; set; }
        public bool NeedCheckpoints { get; set; }
        public bool NeedWorkList { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Specialist Specialist { get; set; }
        public virtual TaskCategory TaskCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskCheckpoint> TaskCheckpoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskClaim> TaskClaim1 { get; set; }
        public virtual TaskClaim TaskClaim2 { get; set; }
        public virtual TaskImportant TaskImportant { get; set; }
        public virtual TaskQuickly TaskQuickly { get; set; }
        public virtual TaskState TaskState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskComment> TaskComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskFile> TaskFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskPlan> TaskPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskAction> TaskAction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskSpecification> TaskSpecification { get; set; }
    }
}
