//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskSpecification
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> QuantityTypeId { get; set; }
        public System.DateTime DateCreate { get; set; }
        public bool Enabled { get; set; }
        public int TaskId { get; set; }
    
        public virtual QuantityType QuantityType { get; set; }
        public virtual TaskClaim TaskClaim { get; set; }
    }
}
