//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskCheckpoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskCheckpoint()
        {
            this.TaskPlan = new HashSet<TaskPlan>();
        }
    
        public int TaskCheckpointId { get; set; }
        public int TaskId { get; set; }
        public string Name { get; set; }
        public bool Done { get; set; }
        public string CreatorSid { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<System.DateTime> DateDone { get; set; }
        public string DonerSid { get; set; }
        public bool Enabled { get; set; }
        public string DeleterSid { get; set; }
        public Nullable<System.DateTime> DateDelete { get; set; }
        public int OrderNum { get; set; }
        public Nullable<System.DateTime> DateUndone { get; set; }
        public string UndonerSid { get; set; }
        public Nullable<int> Hours { get; set; }
    
        public virtual TaskClaim TaskClaim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskPlan> TaskPlan { get; set; }
    }
}
