//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task2TaskState
    {
        public int TaskStateHistoryId { get; set; }
        public int TaskId { get; set; }
        public int TaskStateId { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string CreatorSid { get; set; }
        public string Descr { get; set; }
    
        public virtual TaskState TaskState { get; set; }
    }
}
