//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskFile
    {
        public System.Guid TaskFileId { get; set; }
        public int TaskClaimId { get; set; }
        public string Name { get; set; }
        public byte[] Data { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string CreatorSid { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> DateDelete { get; set; }
        public string DeleterrSid { get; set; }
        public Nullable<int> TaskClaim_TaskId { get; set; }
    
        public virtual TaskClaim TaskClaim { get; set; }
    }
}
