//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTracker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskTrackerEntities : DbContext
    {
        public TaskTrackerEntities()
            : base("name=TaskTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<QuantityType> QuantityType { get; set; }
        public virtual DbSet<Specialist> Specialist { get; set; }
        public virtual DbSet<Task2TaskState> Task2TaskState { get; set; }
        public virtual DbSet<TaskAction> TaskAction { get; set; }
        public virtual DbSet<TaskCategory> TaskCategory { get; set; }
        public virtual DbSet<TaskCheckpoint> TaskCheckpoint { get; set; }
        public virtual DbSet<TaskClaim> TaskClaim { get; set; }
        public virtual DbSet<TaskComment> TaskComment { get; set; }
        public virtual DbSet<TaskFile> TaskFile { get; set; }
        public virtual DbSet<TaskImportant> TaskImportant { get; set; }
        public virtual DbSet<TaskPlan> TaskPlan { get; set; }
        public virtual DbSet<TaskQuickly> TaskQuickly { get; set; }
        public virtual DbSet<TaskSpecification> TaskSpecification { get; set; }
        public virtual DbSet<TaskState> TaskState { get; set; }
        public virtual DbSet<TaskWork> TaskWork { get; set; }
        public virtual DbSet<Wish> Wish { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
