//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskPlan
    {
        public int TaskPlanId { get; set; }
        public int TaskId { get; set; }
        public Nullable<int> TaskCheckpointId { get; set; }
        public System.DateTime PlanDate { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string CreatorSid { get; set; }
        public Nullable<System.DateTime> DateDelete { get; set; }
        public string DeleterSid { get; set; }
    
        public virtual TaskCheckpoint TaskCheckpoint { get; set; }
        public virtual TaskClaim TaskClaim { get; set; }
    }
}
