//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class wish_view
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string Title { get; set; }
        public string Descr { get; set; }
        public string Where { get; set; }
        public string ActionsBefore { get; set; }
        public string Link { get; set; }
        public string CreatorSid { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatorName { get; set; }
        public string ProjectName { get; set; }
        public string ProjectBgColor { get; set; }
        public Nullable<int> StateId { get; set; }
        public string StateChangerSid { get; set; }
        public Nullable<System.DateTime> StateChangeDate { get; set; }
        public string StateDescr { get; set; }
        public string StateChangerName { get; set; }
        public string StateName { get; set; }
    }
}
